-- Object: FCT_TRADES
-- Owner: data-engineering
-- Ticket: PROJ-101
-- Description: Fact table - one row per executed trade. FKs to DIM_ACCOUNT,
--              DIM_SECURITY and DIM_DATE. Loaded nightly by LOAD_FCT_TRADES.
--              PROJ-101: UNIQUE (TRADE_ID) added as defense-in-depth against
--              duplicate trade inserts.

CREATE OR REPLACE TABLE ANALYTICS.MART.FCT_TRADES (
    TRADE_KEY          NUMBER(38,0)  NOT NULL,   -- surrogate key
    TRADE_ID           VARCHAR(30)   NOT NULL,    -- natural/business key
    ACCOUNT_KEY        NUMBER(38,0)  NOT NULL,
    SECURITY_KEY       NUMBER(38,0)  NOT NULL,
    TRADE_DATE_KEY     NUMBER(38,0)  NOT NULL,
    SIDE               VARCHAR(4)    NOT NULL,    -- BUY / SELL
    QUANTITY           NUMBER(28,8)  NOT NULL,
    PRICE              NUMBER(28,8)  NOT NULL,
    GROSS_AMOUNT       NUMBER(28,8)  NOT NULL,
    FEE_AMOUNT         NUMBER(28,8)  NOT NULL DEFAULT 0,
    NET_AMOUNT         NUMBER(28,8)  NOT NULL,
    LOAD_TIMESTAMP     TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_FCT_TRADES PRIMARY KEY (TRADE_KEY),
    CONSTRAINT UQ_FCT_TRADES_TRADE_ID UNIQUE (TRADE_ID),
    CONSTRAINT FK_FCT_TRADES_ACCOUNT  FOREIGN KEY (ACCOUNT_KEY)    REFERENCES ANALYTICS.MART.DIM_ACCOUNT  (ACCOUNT_KEY),
    CONSTRAINT FK_FCT_TRADES_SECURITY FOREIGN KEY (SECURITY_KEY)   REFERENCES ANALYTICS.MART.DIM_SECURITY (SECURITY_KEY),
    CONSTRAINT FK_FCT_TRADES_DATE     FOREIGN KEY (TRADE_DATE_KEY) REFERENCES ANALYTICS.MART.DIM_DATE     (DATE_KEY)
);
