-- Object: VW_DAILY_POSITIONS
-- Owner: data-engineering
-- Ticket: SEED-0001
-- Description: Daily net position per account / security / trade date, derived
--              from FCT_TRADES. SELL reduces quantity, BUY increases it.

CREATE OR REPLACE VIEW ANALYTICS.MART.VW_DAILY_POSITIONS AS
SELECT
    ACC.ACCOUNT_ID,
    ACC.ACCOUNT_NAME,
    SEC.SYMBOL,
    SEC.SECURITY_NAME,
    DT.CALENDAR_DATE                                          AS TRADE_DATE,
    SUM(CASE WHEN FT.SIDE = 'BUY'  THEN FT.QUANTITY ELSE 0 END) AS BUY_QUANTITY,
    SUM(CASE WHEN FT.SIDE = 'SELL' THEN FT.QUANTITY ELSE 0 END) AS SELL_QUANTITY,
    SUM(CASE WHEN FT.SIDE = 'BUY'  THEN FT.QUANTITY ELSE -FT.QUANTITY END) AS NET_QUANTITY,
    SUM(FT.NET_AMOUNT)                                        AS NET_AMOUNT
FROM ANALYTICS.MART.FCT_TRADES FT
JOIN ANALYTICS.MART.DIM_ACCOUNT  ACC ON ACC.ACCOUNT_KEY  = FT.ACCOUNT_KEY
JOIN ANALYTICS.MART.DIM_SECURITY SEC ON SEC.SECURITY_KEY = FT.SECURITY_KEY
JOIN ANALYTICS.MART.DIM_DATE     DT  ON DT.DATE_KEY      = FT.TRADE_DATE_KEY
GROUP BY
    ACC.ACCOUNT_ID,
    ACC.ACCOUNT_NAME,
    SEC.SYMBOL,
    SEC.SECURITY_NAME,
    DT.CALENDAR_DATE;
